import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {articles.map((article, map) =>(
          <Link href={`/${article.slug}`}>
            <a>{article.title}</a>
          </Link>
        ))}
      </main>
    </div>
  )
}

export async function getStaticProps(){
  const url = process.env.API_URL;
  const res = await fetch(`${url}/articles`);
  const articles = await res.json;

  return {
    props: { articles }
  }
}